export const SET_FILTERS = "SET_FILTERS"
export const SET_POST_CODE = "SET_POST_CODE"
export const SET_FROM_AVAILABILITY = "SET_FROM_AVAILABILITY"
export const SET_TO_AVAILABILITY = "SET_TO_AVAILABILITY"
export const SET_EXPERIENCE = "SET_EXPERIENCE"

export const SET_CENTER = "SET_CENTER"
export const RESET_NEAREST_WALKERS = "RESET_NEAREST_WALKERS"
export const ADD_NEAREST_WALKERS = "ADD_NEAREST_WALKERS"
